### ISSUE TITLE
LTE/voLTE Not working for Airtel(Indian Operator)

### ISSUE THREAD

**Issue by darkRaspberry** [PixelExperience-Devices/device_xiaomi_land#2]
Volte service not working for any operator in India. For some operator only LTE are working like JIO.
Again For major operator like Airtel, LTE or voLTE service are not working. Only GSM/WCDMA is working. If the network is set to LTE only. This show no network.
Hope you will help. I will provide you if u need any log.

Please atleast provide LTE .

**Comment by darkRaspberry** [comment]
I have commented on your commit with lots of data. Hope you have time to read.

**Comment by JacobDeepu** [comment]
Have you checked the issue in new update ?

**Comment by darkRaspberry** [comment]
I have tested MCC- 405, MNC-856 carrier(IND JIO). Still no VoLTE. My phone on MIUI work on VoLTE on this carrier. But on PE video call not supported. The same SIM card works correct on the other phone.
I have included some IMS and carrier setting as screenshots. Hope this will help u. See the notification bar doesn't contain VoLTE icon. i have set the network to LTE only. I can Provide additional log If u want. The carrier i am using is one of the largest carrier in India.

Will comment for more carrier soon.


![Screenshot_20200319-155604 1](https://user-images.githubusercontent.com/56693429/77058282-3d0a1480-69fb-11ea-992b-ac5ee82cffa2.png)
![Screenshot_20200319-155618](https://user-images.githubusercontent.com/56693429/77058356-54490200-69fb-11ea-9fc4-e86235bde7ac.png)
![Screenshot_20200319-155615](https://user-images.githubusercontent.com/56693429/77058360-56ab5c00-69fb-11ea-9f75-6f88c938e652.png)

**Comment by darkRaspberry** [comment]
**Note**
1. This is for PE.
2. Flash type - Dirty Flash
3. No module installed(Except Magisk manager)

**Comment by JacobDeepu** [comment]
PE doesn't have volte icon. Volte working for me with jio. No other Airtel users reported the issue.

**Comment by darkRaspberry** [comment]
Seems ok. Will flash MIUI on my device to check any hardware issue again. Thanks for your support.
